package com.plugwine.domain.model;

// Generated Jun 9, 2014 11:41:12 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ApplicationVersionStageActivity generated by hbm2java
 */
public class ApplicationVersionStageActivity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 344583928684434901L;
	private int id;
	private Component component;
	private ApplicationVersionStage applicationVersionStage;
	private int serverId;
	private String workflowActivityId;
	private Set<ConfigurationVariableValue> configurationVariableValues = new HashSet<ConfigurationVariableValue>(
			0);

	public ApplicationVersionStageActivity() {
	}

	public ApplicationVersionStageActivity(int id, Component component,
			ApplicationVersionStage applicationVersionStage, int serverId,
			String workflowActivityId) {
		this.id = id;
		this.component = component;
		this.applicationVersionStage = applicationVersionStage;
		this.serverId = serverId;
		this.workflowActivityId = workflowActivityId;
	}

	public ApplicationVersionStageActivity(int id, Component component,
			ApplicationVersionStage applicationVersionStage, int serverId,
			String workflowActivityId,
			Set<ConfigurationVariableValue> configurationVariableValues) {
		this.id = id;
		this.component = component;
		this.applicationVersionStage = applicationVersionStage;
		this.serverId = serverId;
		this.workflowActivityId = workflowActivityId;
		this.configurationVariableValues = configurationVariableValues;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Component getComponent() {
		return this.component;
	}

	public void setComponent(Component component) {
		this.component = component;
	}

	public ApplicationVersionStage getApplicationVersionStage() {
		return this.applicationVersionStage;
	}

	public void setApplicationVersionStage(
			ApplicationVersionStage applicationVersionStage) {
		this.applicationVersionStage = applicationVersionStage;
	}

	public int getServerId() {
		return this.serverId;
	}

	public void setServerId(int serverId) {
		this.serverId = serverId;
	}

	public String getWorkflowActivityId() {
		return this.workflowActivityId;
	}

	public void setWorkflowActivityId(String workflowActivityId) {
		this.workflowActivityId = workflowActivityId;
	}

	public Set<ConfigurationVariableValue> getConfigurationVariableValues() {
		return this.configurationVariableValues;
	}

	public void setConfigurationVariableValues(
			Set<ConfigurationVariableValue> configurationVariableValues) {
		this.configurationVariableValues = configurationVariableValues;
	}

}
