package com.plugwine.domain.model;

// Generated Jun 9, 2014 11:41:12 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ApplicationVersion generated by hbm2java
 */
public class ApplicationVersion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7837410858465266381L;
	private int id;
	private ReleasePath releasePath;
	private Serializable name;
	private int statusId;
	private int teamFoundationServerId;
	private int teamProjectCollectionId;
	private Serializable teamProject;
	private Serializable buildDefinition;
	private Serializable notes;
	private Serializable description;
	private boolean canTriggerReleaseFromBuild;
	private Date createdOn;
	private int createdById;
	private Date modifiedOn;
	private int modifiedById;
	private Date lockedOn;
	private int lockedById;
	private int unLockedById;
	private Serializable lockedSessionId;
	private boolean isDeleted;
	private Set<ApplicationVersionStage> applicationVersionStages = new HashSet<ApplicationVersionStage>(
			0);

	public ApplicationVersion() {
	}

	public ApplicationVersion(int id, ReleasePath releasePath,
			Serializable name, int statusId, int teamFoundationServerId,
			int teamProjectCollectionId, Serializable teamProject,
			Serializable buildDefinition, Serializable notes,
			Serializable description, boolean canTriggerReleaseFromBuild,
			Date createdOn, int createdById, Date modifiedOn, int modifiedById,
			Date lockedOn, int lockedById, int unLockedById,
			Serializable lockedSessionId, boolean isDeleted) {
		this.id = id;
		this.releasePath = releasePath;
		this.name = name;
		this.statusId = statusId;
		this.teamFoundationServerId = teamFoundationServerId;
		this.teamProjectCollectionId = teamProjectCollectionId;
		this.teamProject = teamProject;
		this.buildDefinition = buildDefinition;
		this.notes = notes;
		this.description = description;
		this.canTriggerReleaseFromBuild = canTriggerReleaseFromBuild;
		this.createdOn = createdOn;
		this.createdById = createdById;
		this.modifiedOn = modifiedOn;
		this.modifiedById = modifiedById;
		this.lockedOn = lockedOn;
		this.lockedById = lockedById;
		this.unLockedById = unLockedById;
		this.lockedSessionId = lockedSessionId;
		this.isDeleted = isDeleted;
	}

	public ApplicationVersion(int id, ReleasePath releasePath,
			Serializable name, int statusId, int teamFoundationServerId,
			int teamProjectCollectionId, Serializable teamProject,
			Serializable buildDefinition, Serializable notes,
			Serializable description, boolean canTriggerReleaseFromBuild,
			Date createdOn, int createdById, Date modifiedOn, int modifiedById,
			Date lockedOn, int lockedById, int unLockedById,
			Serializable lockedSessionId, boolean isDeleted,
			Set<ApplicationVersionStage> applicationVersionStages) {
		this.id = id;
		this.releasePath = releasePath;
		this.name = name;
		this.statusId = statusId;
		this.teamFoundationServerId = teamFoundationServerId;
		this.teamProjectCollectionId = teamProjectCollectionId;
		this.teamProject = teamProject;
		this.buildDefinition = buildDefinition;
		this.notes = notes;
		this.description = description;
		this.canTriggerReleaseFromBuild = canTriggerReleaseFromBuild;
		this.createdOn = createdOn;
		this.createdById = createdById;
		this.modifiedOn = modifiedOn;
		this.modifiedById = modifiedById;
		this.lockedOn = lockedOn;
		this.lockedById = lockedById;
		this.unLockedById = unLockedById;
		this.lockedSessionId = lockedSessionId;
		this.isDeleted = isDeleted;
		this.applicationVersionStages = applicationVersionStages;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ReleasePath getReleasePath() {
		return this.releasePath;
	}

	public void setReleasePath(ReleasePath releasePath) {
		this.releasePath = releasePath;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	public int getTeamFoundationServerId() {
		return this.teamFoundationServerId;
	}

	public void setTeamFoundationServerId(int teamFoundationServerId) {
		this.teamFoundationServerId = teamFoundationServerId;
	}

	public int getTeamProjectCollectionId() {
		return this.teamProjectCollectionId;
	}

	public void setTeamProjectCollectionId(int teamProjectCollectionId) {
		this.teamProjectCollectionId = teamProjectCollectionId;
	}

	public Serializable getTeamProject() {
		return this.teamProject;
	}

	public void setTeamProject(Serializable teamProject) {
		this.teamProject = teamProject;
	}

	public Serializable getBuildDefinition() {
		return this.buildDefinition;
	}

	public void setBuildDefinition(Serializable buildDefinition) {
		this.buildDefinition = buildDefinition;
	}

	public Serializable getNotes() {
		return this.notes;
	}

	public void setNotes(Serializable notes) {
		this.notes = notes;
	}

	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	public boolean isCanTriggerReleaseFromBuild() {
		return this.canTriggerReleaseFromBuild;
	}

	public void setCanTriggerReleaseFromBuild(boolean canTriggerReleaseFromBuild) {
		this.canTriggerReleaseFromBuild = canTriggerReleaseFromBuild;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public int getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(int createdById) {
		this.createdById = createdById;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public int getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(int modifiedById) {
		this.modifiedById = modifiedById;
	}

	public Date getLockedOn() {
		return this.lockedOn;
	}

	public void setLockedOn(Date lockedOn) {
		this.lockedOn = lockedOn;
	}

	public int getLockedById() {
		return this.lockedById;
	}

	public void setLockedById(int lockedById) {
		this.lockedById = lockedById;
	}

	public int getUnLockedById() {
		return this.unLockedById;
	}

	public void setUnLockedById(int unLockedById) {
		this.unLockedById = unLockedById;
	}

	public Serializable getLockedSessionId() {
		return this.lockedSessionId;
	}

	public void setLockedSessionId(Serializable lockedSessionId) {
		this.lockedSessionId = lockedSessionId;
	}

	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Set<ApplicationVersionStage> getApplicationVersionStages() {
		return this.applicationVersionStages;
	}

	public void setApplicationVersionStages(
			Set<ApplicationVersionStage> applicationVersionStages) {
		this.applicationVersionStages = applicationVersionStages;
	}

}
