package com.plugwine.domain.model;

// Generated Jun 9, 2014 11:41:12 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ApplicationVersionStage generated by hbm2java
 */
public class ApplicationVersionStage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5534321316342866892L;
	private int id;
	private ApplicationVersion applicationVersion;
	private Stage stage;
	private Serializable workflow;
	private Set<ApplicationVersionStageActivity> applicationVersionStageActivities = new HashSet<ApplicationVersionStageActivity>(
			0);

	public ApplicationVersionStage() {
	}

	public ApplicationVersionStage(int id,
			ApplicationVersion applicationVersion, Stage stage) {
		this.id = id;
		this.applicationVersion = applicationVersion;
		this.stage = stage;
	}

	public ApplicationVersionStage(
			int id,
			ApplicationVersion applicationVersion,
			Stage stage,
			Serializable workflow,
			Set<ApplicationVersionStageActivity> applicationVersionStageActivities) {
		this.id = id;
		this.applicationVersion = applicationVersion;
		this.stage = stage;
		this.workflow = workflow;
		this.applicationVersionStageActivities = applicationVersionStageActivities;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ApplicationVersion getApplicationVersion() {
		return this.applicationVersion;
	}

	public void setApplicationVersion(ApplicationVersion applicationVersion) {
		this.applicationVersion = applicationVersion;
	}

	public Stage getStage() {
		return this.stage;
	}

	public void setStage(Stage stage) {
		this.stage = stage;
	}

	public Serializable getWorkflow() {
		return this.workflow;
	}

	public void setWorkflow(Serializable workflow) {
		this.workflow = workflow;
	}

	public Set<ApplicationVersionStageActivity> getApplicationVersionStageActivities() {
		return this.applicationVersionStageActivities;
	}

	public void setApplicationVersionStageActivities(
			Set<ApplicationVersionStageActivity> applicationVersionStageActivities) {
		this.applicationVersionStageActivities = applicationVersionStageActivities;
	}

}
