package com.plugwine.domain.model;

// Generated Jun 9, 2014 11:41:12 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Component generated by hbm2java
 */
public class Component implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1032268989475621297L;
	private int id;
	private Serializable name;
	private int statusId;
	private Serializable packageLocation;
	private Serializable fileExtensionFilter;
	private int deployerToolId;
	private Serializable command;
	private Serializable arguments;
	private int timeout;
	private int variableReplacementModeId;
	private Serializable description;
	private int typeId;
	private int teamFoundationServerId;
	private int teamProjectCollectionId;
	private Serializable teamProject;
	private Serializable buildDefinition;
	private int actionTypeId;
	private Date createdOn;
	private int createdById;
	private Date modifiedOn;
	private int modifiedById;
	private boolean isDeleted;
	private boolean isPublishedByMicrosoft;
	private Set<ConfigurationVariable> configurationVariables = new HashSet<ConfigurationVariable>(
			0);
	private Set<ApplicationVersionStageActivity> applicationVersionStageActivities = new HashSet<ApplicationVersionStageActivity>(
			0);

	public Component() {
	}

	public Component(int id, Serializable name, int statusId,
			Serializable packageLocation, Serializable fileExtensionFilter,
			int deployerToolId, Serializable command, Serializable arguments,
			int timeout, int variableReplacementModeId,
			Serializable description, int typeId, int teamFoundationServerId,
			int teamProjectCollectionId, Serializable teamProject,
			Serializable buildDefinition, int actionTypeId, Date createdOn,
			int createdById, Date modifiedOn, int modifiedById,
			boolean isDeleted, boolean isPublishedByMicrosoft) {
		this.id = id;
		this.name = name;
		this.statusId = statusId;
		this.packageLocation = packageLocation;
		this.fileExtensionFilter = fileExtensionFilter;
		this.deployerToolId = deployerToolId;
		this.command = command;
		this.arguments = arguments;
		this.timeout = timeout;
		this.variableReplacementModeId = variableReplacementModeId;
		this.description = description;
		this.typeId = typeId;
		this.teamFoundationServerId = teamFoundationServerId;
		this.teamProjectCollectionId = teamProjectCollectionId;
		this.teamProject = teamProject;
		this.buildDefinition = buildDefinition;
		this.actionTypeId = actionTypeId;
		this.createdOn = createdOn;
		this.createdById = createdById;
		this.modifiedOn = modifiedOn;
		this.modifiedById = modifiedById;
		this.isDeleted = isDeleted;
		this.isPublishedByMicrosoft = isPublishedByMicrosoft;
	}

	public Component(
			int id,
			Serializable name,
			int statusId,
			Serializable packageLocation,
			Serializable fileExtensionFilter,
			int deployerToolId,
			Serializable command,
			Serializable arguments,
			int timeout,
			int variableReplacementModeId,
			Serializable description,
			int typeId,
			int teamFoundationServerId,
			int teamProjectCollectionId,
			Serializable teamProject,
			Serializable buildDefinition,
			int actionTypeId,
			Date createdOn,
			int createdById,
			Date modifiedOn,
			int modifiedById,
			boolean isDeleted,
			boolean isPublishedByMicrosoft,
			Set<ConfigurationVariable> configurationVariables,
			Set<ApplicationVersionStageActivity> applicationVersionStageActivities) {
		this.id = id;
		this.name = name;
		this.statusId = statusId;
		this.packageLocation = packageLocation;
		this.fileExtensionFilter = fileExtensionFilter;
		this.deployerToolId = deployerToolId;
		this.command = command;
		this.arguments = arguments;
		this.timeout = timeout;
		this.variableReplacementModeId = variableReplacementModeId;
		this.description = description;
		this.typeId = typeId;
		this.teamFoundationServerId = teamFoundationServerId;
		this.teamProjectCollectionId = teamProjectCollectionId;
		this.teamProject = teamProject;
		this.buildDefinition = buildDefinition;
		this.actionTypeId = actionTypeId;
		this.createdOn = createdOn;
		this.createdById = createdById;
		this.modifiedOn = modifiedOn;
		this.modifiedById = modifiedById;
		this.isDeleted = isDeleted;
		this.isPublishedByMicrosoft = isPublishedByMicrosoft;
		this.configurationVariables = configurationVariables;
		this.applicationVersionStageActivities = applicationVersionStageActivities;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	public Serializable getPackageLocation() {
		return this.packageLocation;
	}

	public void setPackageLocation(Serializable packageLocation) {
		this.packageLocation = packageLocation;
	}

	public Serializable getFileExtensionFilter() {
		return this.fileExtensionFilter;
	}

	public void setFileExtensionFilter(Serializable fileExtensionFilter) {
		this.fileExtensionFilter = fileExtensionFilter;
	}

	public int getDeployerToolId() {
		return this.deployerToolId;
	}

	public void setDeployerToolId(int deployerToolId) {
		this.deployerToolId = deployerToolId;
	}

	public Serializable getCommand() {
		return this.command;
	}

	public void setCommand(Serializable command) {
		this.command = command;
	}

	public Serializable getArguments() {
		return this.arguments;
	}

	public void setArguments(Serializable arguments) {
		this.arguments = arguments;
	}

	public int getTimeout() {
		return this.timeout;
	}

	public void setTimeout(int timeout) {
		this.timeout = timeout;
	}

	public int getVariableReplacementModeId() {
		return this.variableReplacementModeId;
	}

	public void setVariableReplacementModeId(int variableReplacementModeId) {
		this.variableReplacementModeId = variableReplacementModeId;
	}

	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	public int getTypeId() {
		return this.typeId;
	}

	public void setTypeId(int typeId) {
		this.typeId = typeId;
	}

	public int getTeamFoundationServerId() {
		return this.teamFoundationServerId;
	}

	public void setTeamFoundationServerId(int teamFoundationServerId) {
		this.teamFoundationServerId = teamFoundationServerId;
	}

	public int getTeamProjectCollectionId() {
		return this.teamProjectCollectionId;
	}

	public void setTeamProjectCollectionId(int teamProjectCollectionId) {
		this.teamProjectCollectionId = teamProjectCollectionId;
	}

	public Serializable getTeamProject() {
		return this.teamProject;
	}

	public void setTeamProject(Serializable teamProject) {
		this.teamProject = teamProject;
	}

	public Serializable getBuildDefinition() {
		return this.buildDefinition;
	}

	public void setBuildDefinition(Serializable buildDefinition) {
		this.buildDefinition = buildDefinition;
	}

	public int getActionTypeId() {
		return this.actionTypeId;
	}

	public void setActionTypeId(int actionTypeId) {
		this.actionTypeId = actionTypeId;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public int getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(int createdById) {
		this.createdById = createdById;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public int getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(int modifiedById) {
		this.modifiedById = modifiedById;
	}

	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public boolean isIsPublishedByMicrosoft() {
		return this.isPublishedByMicrosoft;
	}

	public void setIsPublishedByMicrosoft(boolean isPublishedByMicrosoft) {
		this.isPublishedByMicrosoft = isPublishedByMicrosoft;
	}

	public Set<ConfigurationVariable> getConfigurationVariables() {
		return this.configurationVariables;
	}

	public void setConfigurationVariables(
			Set<ConfigurationVariable> configurationVariables) {
		this.configurationVariables = configurationVariables;
	}

	public Set<ApplicationVersionStageActivity> getApplicationVersionStageActivities() {
		return this.applicationVersionStageActivities;
	}

	public void setApplicationVersionStageActivities(
			Set<ApplicationVersionStageActivity> applicationVersionStageActivities) {
		this.applicationVersionStageActivities = applicationVersionStageActivities;
	}

}
