package com.plugwine.domain.model;

// Generated Jun 9, 2014 11:41:12 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * ConfigurationVariableValueId generated by hbm2java
 */
public class ConfigurationVariableValueId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3711202329396914441L;
	private int id;
	private int applicationVersionStageActivityId;
	private int configurationVariableId;
	private Integer serverId;
	private Serializable value;

	public ConfigurationVariableValueId() {
	}

	public ConfigurationVariableValueId(int id,
			int applicationVersionStageActivityId, int configurationVariableId,
			Serializable value) {
		this.id = id;
		this.applicationVersionStageActivityId = applicationVersionStageActivityId;
		this.configurationVariableId = configurationVariableId;
		this.value = value;
	}

	public ConfigurationVariableValueId(int id,
			int applicationVersionStageActivityId, int configurationVariableId,
			Integer serverId, Serializable value) {
		this.id = id;
		this.applicationVersionStageActivityId = applicationVersionStageActivityId;
		this.configurationVariableId = configurationVariableId;
		this.serverId = serverId;
		this.value = value;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getApplicationVersionStageActivityId() {
		return this.applicationVersionStageActivityId;
	}

	public void setApplicationVersionStageActivityId(
			int applicationVersionStageActivityId) {
		this.applicationVersionStageActivityId = applicationVersionStageActivityId;
	}

	public int getConfigurationVariableId() {
		return this.configurationVariableId;
	}

	public void setConfigurationVariableId(int configurationVariableId) {
		this.configurationVariableId = configurationVariableId;
	}

	public Integer getServerId() {
		return this.serverId;
	}

	public void setServerId(Integer serverId) {
		this.serverId = serverId;
	}

	public Serializable getValue() {
		return this.value;
	}

	public void setValue(Serializable value) {
		this.value = value;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConfigurationVariableValueId))
			return false;
		ConfigurationVariableValueId castOther = (ConfigurationVariableValueId) other;

		return (this.getId() == castOther.getId())
				&& (this.getApplicationVersionStageActivityId() == castOther
						.getApplicationVersionStageActivityId())
				&& (this.getConfigurationVariableId() == castOther
						.getConfigurationVariableId())
				&& ((this.getServerId() == castOther.getServerId()) || (this
						.getServerId() != null
						&& castOther.getServerId() != null && this
						.getServerId().equals(castOther.getServerId())))
				&& ((this.getValue() == castOther.getValue()) || (this
						.getValue() != null && castOther.getValue() != null && this
						.getValue().equals(castOther.getValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getApplicationVersionStageActivityId();
		result = 37 * result + this.getConfigurationVariableId();
		result = 37 * result
				+ (getServerId() == null ? 0 : this.getServerId().hashCode());
		result = 37 * result
				+ (getValue() == null ? 0 : this.getValue().hashCode());
		return result;
	}

}
