package com.plugwine.domain.model;

// Generated Jun 9, 2014 11:41:12 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ConfigurationVariable generated by hbm2java
 */
public class ConfigurationVariable implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6540964915362623474L;
	private int id;
	private Component component;
	private Serializable name;
	private int typeId;
	private Serializable description;
	private boolean isSystem;
	private boolean isDeleted;
	private boolean isParameter;
	private Set<ConfigurationVariableValue> configurationVariableValues = new HashSet<ConfigurationVariableValue>(
			0);

	public ConfigurationVariable() {
	}

	public ConfigurationVariable(int id, Component component,
			Serializable name, int typeId, Serializable description,
			boolean isSystem, boolean isDeleted, boolean isParameter) {
		this.id = id;
		this.component = component;
		this.name = name;
		this.typeId = typeId;
		this.description = description;
		this.isSystem = isSystem;
		this.isDeleted = isDeleted;
		this.isParameter = isParameter;
	}

	public ConfigurationVariable(int id, Component component,
			Serializable name, int typeId, Serializable description,
			boolean isSystem, boolean isDeleted, boolean isParameter,
			Set<ConfigurationVariableValue> configurationVariableValues) {
		this.id = id;
		this.component = component;
		this.name = name;
		this.typeId = typeId;
		this.description = description;
		this.isSystem = isSystem;
		this.isDeleted = isDeleted;
		this.isParameter = isParameter;
		this.configurationVariableValues = configurationVariableValues;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Component getComponent() {
		return this.component;
	}

	public void setComponent(Component component) {
		this.component = component;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public int getTypeId() {
		return this.typeId;
	}

	public void setTypeId(int typeId) {
		this.typeId = typeId;
	}

	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	public boolean isIsSystem() {
		return this.isSystem;
	}

	public void setIsSystem(boolean isSystem) {
		this.isSystem = isSystem;
	}

	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public boolean isIsParameter() {
		return this.isParameter;
	}

	public void setIsParameter(boolean isParameter) {
		this.isParameter = isParameter;
	}

	public Set<ConfigurationVariableValue> getConfigurationVariableValues() {
		return this.configurationVariableValues;
	}

	public void setConfigurationVariableValues(
			Set<ConfigurationVariableValue> configurationVariableValues) {
		this.configurationVariableValues = configurationVariableValues;
	}

}
