package com.plugwine.domain.model;

// Generated Jun 9, 2014 11:41:12 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ReleasePath generated by hbm2java
 */
public class ReleasePath implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = -7797559366396446538L;
	private int id;
	private Serializable name;
	private Serializable description;
	private int statusId;
	private Date createdOn;
	private int createdById;
	private Date modifiedOn;
	private int modifiedById;
	private boolean isDeleted;
	private Set<Stage> stages = new HashSet<Stage>(0);
	private Set<ApplicationVersion> applicationVersions = new HashSet<ApplicationVersion>(
			0);

	public ReleasePath() {
	}

	public ReleasePath(int id, Serializable name, Serializable description,
			int statusId, Date createdOn, int createdById, Date modifiedOn,
			int modifiedById, boolean isDeleted) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.statusId = statusId;
		this.createdOn = createdOn;
		this.createdById = createdById;
		this.modifiedOn = modifiedOn;
		this.modifiedById = modifiedById;
		this.isDeleted = isDeleted;
	}

	public ReleasePath(int id, Serializable name, Serializable description,
			int statusId, Date createdOn, int createdById, Date modifiedOn,
			int modifiedById, boolean isDeleted, Set<Stage> stages,
			Set<ApplicationVersion> applicationVersions) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.statusId = statusId;
		this.createdOn = createdOn;
		this.createdById = createdById;
		this.modifiedOn = modifiedOn;
		this.modifiedById = modifiedById;
		this.isDeleted = isDeleted;
		this.stages = stages;
		this.applicationVersions = applicationVersions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public int getCreatedById() {
		return this.createdById;
	}

	public void setCreatedById(int createdById) {
		this.createdById = createdById;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public int getModifiedById() {
		return this.modifiedById;
	}

	public void setModifiedById(int modifiedById) {
		this.modifiedById = modifiedById;
	}

	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Set<Stage> getStages() {
		return this.stages;
	}

	public void setStages(Set<Stage> stages) {
		this.stages = stages;
	}

	public Set<ApplicationVersion> getApplicationVersions() {
		return this.applicationVersions;
	}

	public void setApplicationVersions(
			Set<ApplicationVersion> applicationVersions) {
		this.applicationVersions = applicationVersions;
	}

}
