package com.plugwine.domain.model;

// Generated Jun 9, 2014 11:41:12 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Stage generated by hbm2java
 */
public class Stage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7970403523758797498L;
	private int id;
	private StageType stageType;
	private ReleasePath releasePath;
	private Integer environmentId;
	private int rank;
	private boolean isDeleted;
	private Set<ApplicationVersionStage> applicationVersionStages = new HashSet<ApplicationVersionStage>(0);

	public Stage() {
	}

	public Stage(int id, StageType stageType, ReleasePath releasePath,
			int rank, boolean isDeleted) {
		this.id = id;
		this.stageType = stageType;
		this.releasePath = releasePath;
		this.rank = rank;
		this.isDeleted = isDeleted;
	}

	public Stage(int id, StageType stageType, ReleasePath releasePath,
			Integer environmentId, int rank, boolean isDeleted,
			Set<ApplicationVersionStage> applicationVersionStages) {
		this.id = id;
		this.stageType = stageType;
		this.releasePath = releasePath;
		this.environmentId = environmentId;
		this.rank = rank;
		this.isDeleted = isDeleted;
		this.applicationVersionStages = applicationVersionStages;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public StageType getStageType() {
		return this.stageType;
	}

	public void setStageType(StageType stageType) {
		this.stageType = stageType;
	}

	public ReleasePath getReleasePath() {
		return this.releasePath;
	}

	public void setReleasePath(ReleasePath releasePath) {
		this.releasePath = releasePath;
	}

	public Integer getEnvironmentId() {
		return this.environmentId;
	}

	public void setEnvironmentId(Integer environmentId) {
		this.environmentId = environmentId;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Set<ApplicationVersionStage> getApplicationVersionStages() {
		return this.applicationVersionStages;
	}

	public void setApplicationVersionStages(
			Set<ApplicationVersionStage> applicationVersionStages) {
		this.applicationVersionStages = applicationVersionStages;
	}

}
